### ISSUE TITLE
what's the time horizon & how often should we meet?

### ISSUE THREAD

**Issue by masinter** [masinter/pdf-data-cg-charter#8]
I'm leaning toward a weekly meeting and some focus, but that the group should have a short time horizon -- plan to be done in 6 months? If feasible; any case no more than a year.

The charter should be ready for approval in September, but we could get started sooner on most of the deliverables.

**Comment by hjellinek** [comment]
I like the idea of a weekly meeting and a short time horizon, but I don't yet have a good sense of exactly what we're hoping to accomplish by that time.

**Comment by masinter** [comment]
Perhaps the question should be what CAN we get done when?

## 

http://larry.masinter.net

On Jul 21, 2016, at 3:23 PM, Herb Jellinek <notifications@github.com<mailto:notifications@github.com>> wrote:

I like the idea of a weekly meeting and a short time horizon, but I don't yet have a good sense of exactly what we're hoping to accomplish by that time.

##

**Comment by masinter** [comment]
initial guidelines broadened in thee charter
